### ISSUE TITLE
Cloud functions for deleting messages after 24 hours

### ISSUE THREAD

**Issue by walidboulanouar** [sunanda35/WhatzChat#2]
I can't find the cloud functions of deleting messages after 24 hours, i really need it for my project if you don't have any problem can you provide me this cloud functions

**Comment by sunanda35** [comment]
this facility is not available in this project. But you can do it by using time triggered function. Or create a function which will triggered one time in a day, and delete all chats which time is more than 24 hours. Otherwise, if you do it for every chat, you will burn ur money, nothing else, this is my suggestion.
